title: "tommbirui6"
tagline: "Personal Portfolio and Blog"
description: "Welcome to my personal website"
url: "https://tommbirui6.github.io"  # Don't include a trailing slash
baseurl: ""  # Keep this empty for user.github.io sites

lang: "en"
timezone: "Africa/Nairobi"

theme: jekyll-theme-chirpy

author:
  name: "Tom Mbiru"
  email: "tommbiru@example.com"   # <-- replace with your real email
  url: "https://tommbirui6.github.io"

github:
  username: tommbirui6

social:
  name: "Tom Mbiru"
  email: "tommbiru@example.com"   # <-- same here
  links:
    - https://github.com/tommbirui6
    - https://linkedin.com/in/tommbiru   # <-- replace with your LinkedIn handle

markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - vendor
  - README.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Tom Mbiru"


  
