title: "tommbirui6"
tagline: "Personal Portfolio and Blog"
description: "Welcome to my personal website"
url: "https://tommbirui6.github.io"  # No trailing slash
baseurl: ""  # Keep this empty for user.github.io repo

lang: "en"
timezone: "Africa/Nairobi"

theme: jekyll-theme-chirpy

author:
  name: "Tom Mbiru"
  email: "your-email@example.com"
  url: "https://tommbirui6.github.io"

github:
  username: tommbirui6

twitter:
  username: your_twitter_handle  # Optional

social:
  name: "Tom Mbiru"
  email: "your-email@example.com"
  links:
    - https://github.com/tommbirui6
    - https://linkedin.com/in/your-linkedin  # Optional

paginate: 5
paginate_path: /page:num/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: Google Analytics, Disqus, etc.
# google_analytics:
# disqus:
#   shortname: your-disqus-shortname

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Tom Mbirui"
