title: "tommbirui6"
tagline: "Personal Portfolio and Blog"
description: "Welcome to my personal website"
url: "https://tommbirui6.github.io"  # Don't include a trailing slash
baseurl: ""  # Keep this empty for user.github.io sites

lang: "en"
timezone: "Africa/Nairobi"

theme: jekyll-theme-chirpy

author:
  name: "Tom Mbiru"
  email: "your-email@example.com"
  url: "https://tommbirui6.github.io"

github:
  username: tommbirui6

social:
  name: "Tom Mbiru"
  email: "your-email@example.com"
  links:
    - https://github.com/tommbirui6
    - https://linkedin.com/in/your-linkedin-username  # Optional

markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Tom Mbirui"

  
